CREATE DATABASE IF NOT EXISTS SAMPLE_STAR_SCHEMA;
USE DATABASE SAMPLE_STAR_SCHEMA;
CREATE SCHEMA IF NOT EXISTS GOLD;
USE SCHEMA GOLD;

CREATE TABLE IF NOT EXISTS DimCustomer AS 
SELECT * 
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.CUSTOMER AS CUSTOMER
INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.NATION AS NATION 
ON CUSTOMER.C_NATIONKEY = NATION.N_NATIONKEY
INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.REGION AS REGION 
ON NATION.N_REGIONKEY = REGION.R_REGIONKEY
