CREATE DATABASE IF NOT EXISTS SAMPLE_STAR_SCHEMA;
USE DATABASE SAMPLE_STAR_SCHEMA;
CREATE SCHEMA IF NOT EXISTS GOLD;
USE SCHEMA GOLD;

CREATE TABLE IF NOT EXISTS DimLineItem AS 
SELECT * 
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.LINEITEM AS LINEITEM
INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.PART AS PART 
ON LINEITEM.L_PARTKEY = PART.P_PARTKEY
