CREATE DATABASE IF NOT EXISTS SAMPLE_STAR_SCHEMA;
USE DATABASE SAMPLE_STAR_SCHEMA;
CREATE SCHEMA IF NOT EXISTS GOLD;
USE SCHEMA GOLD;

CREATE TABLE FactOrder AS 
SELECT * 
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.ORDERS

